=== MaxZ87/JD2016/src/by/it/zebnitskiy/JD_02/JD_02_07/2DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT kurss (kurs) +>
        <!ELEMENT kurs (exchange, telephon, address)>
        <!ATTLIST kurs
                unit ID #REQUIRED
                course CDATA  #REQUIRED
                >
        <!ELEMENT exchange ( #PCDATA)>
        <!ELEMENT telephon (#PCDATA)>
        <!ELEMENT address (city, street)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>

=== MaxZ87/JD2016/src/by/it/zebnitskiy/JD_02/JD_02_07/1XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kurss SYSTEM  "2DTD.dtd">
<kurss>
    <kurs unit = "dol"  course = 'Minsk'>
        <exchange>MMB</exchange>
        <telephone>80445501413</telephone>
        <address>
            <city>Minsk</city>
            <street>Nezavicimosty</street>
        </address>
    </kurs>

    <kurs unit = "Eur" course = 'Minsk'>
        <exchange>VTB</exchange>
        <telephon>80297587417</telephon>
        <address>
            <city>Borisov</city>
            <street>Olyshevskogo</street>
        </address>
    </kurs>

    <kurs unit = "Rub" course = 'Minsk'>
        <exchange> VAB</exchange>
        <telephon>80175412358</telephon>
        <address>
            <city>Brest</city>
            <street>Utochka</street>
        </address>
    </kurs>
</kurss>
